export const ACTION_GET_ALBUMS = "ACTION_GET_ALBUMS";
export const ACTION_GET_ALBUMS_RESPONSE = "ACTION_GET_ALBUMS_RESPONSE";
export const ACTION_GET_ALBUMS_FAILED = "ACTION_GET_ALBUMS_FAILED";

export const ACTION_GET_PHOTOS = "ACTION_GET_PHOTOS";
export const ACTION_GET_PHOTOS_RESPONSE = "ACTION_GET_PHOTOS_RESPONSE";
export const ACTION_GET_PHOTOS_FAILED = "ACTION_GET_PHOTOS_FAILED";